### PR TITLE
Added support for multiple _transform functions in collection #46

### PR DESCRIPTION
**Pull request by Kostanos**
This small commit will fix the issue with multiple collection._transformers

### CODE REVIEW

**Comment by dburles** [comment]
I've thought about this functionality in the past and the general reason why it's not part of the source is that it's not a terribly great idea to extend on existing transform functions as it could lead to some very hard to trace bugs (imagine if you had a helper with the same name as one applied by tap-i18n for example). I'll have a think about it some more, potentially it could disallow applying a helper with a method name that already exists, but that's still not ideal...

**Comment by Kostanos** [comment]
if tap-i18n or any other Collection extenders will use the _helpers object inside, it will be different issue.
For the moment both of these and many other packages using _transform function.

If this package will not support multiple _transform, it will be useless in many cases.

BTW. I didn't reinvented the wheal, I copied the _transform support in this commit from tap-i18n package, they did exactly the same approach. Check: https://github.com/TAPevents/tap-i18n-db/blob/master/tap_i18n_db-common.coffee#L4

I still convinced that this support will only help to this package. In my case, I can't use the package without it for sure.

**Comment by dburles** [comment]
Yeah but the difference in that case is that it will be applying it's own *single* transform, after the fact which is less of a problem than in this case where you can add anything!

Perhaps you might get around the issue by placing the i18n package below collection-helpers in your `.meteor/packages` file

**Comment by Kostanos** [comment]
It won't help :) the order of packages is not affecting on the issue.
How i18n works it extends the collection before anyway. Example:

```
Collections.meals = new TAPi18n.Collection('meals', {
  languages: LanguagesList,
  base_language: 'en',
});

Collections.meals.helpers({
  priceText: function(){
    // TODO: Currency converter
    return "RD$ " + this.price;
  }
});
```

And again, the multiple _transform approach is not only helping with i18n but with any other Collection extenders which uses ```_transform``` function.

**Comment by Kostanos** [comment]
In other word, your package without this support monopolize the _transform function and doesn't allow use it for any other package.

**Comment by dburles** [comment]
That's right but I don't feel it's correct for this package to extend on existing transformation functions for the reasons I mentioned in my first post.

**Comment by dburles** [comment]
I believe you're the first person to raise this issue, so it's likely not a problem people run into often

**Comment by Kostanos** [comment]
I didn't get the problem you described actually. But ok, I'll keep using my fork. Thank you anyway.

**Comment by dburles** [comment]
There's no correct way to extend upon existing transform functions, packages should add support for collection-helpers (which is simple enough to do).

**Comment by DanielDornhardt** [comment]
+1 for being able to add your own transform on top of collection-helpers. I like @Kostanos fork and may use it in the future.

It's of course possible to shoot yourself in the foot, but that's more or less always possible in some way or another.

**Pull request closed without merging**
