### PR TITLE
Master

### PR DESCRIPTION
**Pull request by stfnbrgh**
Added support for nesting helpers on embedded documents.

see tests for examples.

### CODE REVIEW

**Comment by rclai** [comment]
The nested properties are not attached to the prototype, wouldn't that be a problem?

**Comment by dburles** [comment]
Hey @stfnbrgh thanks for the pull request, I don't think I'll merge however for a couple of reasons. 

I feel that collection-helpers power lies in its simplicity, whereas the features added in this PR are more suited to more complex projects, it just adds an unnecessary layer therefore I feel that adding further complexity to cover the 10% doesn't feel correct to me.

**Comment by rclai** [comment]
It doesn't seem like you will be able to get at the top-level fields from a nested collection helper.

**Comment by stfnbrgh** [comment]
@dburles - No problem, I will consider a package once it has matured a bit. 

@rclai - Good point, will look into it!

**Comment by boustanihani** [comment]
@dburles Please reconsider merging the pull-rerquest (or perhaps asking for a simplified functionality), IMO having many similar packages on atmosphere would irritate the users...

**Comment by dburles** [comment]
@boustanihani my hesitation to merge is that I've never had a strong requirement for this feature in all of the apps that I have developed since I first created and began using collection-helpers, so I believe it's not the right decision.

However, it's not to say that there aren't projects out there that would benefit from nested helpers, so in that case it seems ideal to me if it could be provided as an "add-on" package for collection-helpers, it would be nice if `nested-collection-helpers` could depend on `collection-helpers` and simply add the extra functionality.

What are your thoughts on this @stfnbrgh?

**Comment by stfnbrgh** [comment]
@dburles I don't know. Because collection-helpers is so simple, wouldn't it be easier to develop it as a replacement for people who require the added complexity. Then they can use either collection-helpers or collection-nested-helpers. 

I'm not sure how I would extend collection-helpers as-is in an efficient way? I no JavaScript guru though so maybe you have some ideas? 

Maybe we could we add extension points to collection-helpers? I'm thinking a chain of key handlers on register that handles the different key's and a handler on attach that has access to the data from register step? 

example: 
"simple" -> add to prototype
"or.nested" -> handle nested
"or.$.array" -> handle nested with arrays

Other packages can the register their handler pairs with collection-helpers?

This will add to complexity to collection-helpers though.

**Comment by Kostanos** [comment]
I vote to keep the code simpler. Why don't think in some scheme of extensions? Like other plugins does.

So if someone need nested functionality he'll add the nested-collections-helpers extension to this one. etc..

**Pull request closed without merging**
